/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package certificaadooracle;

import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author magipedgay
 */
public class certificadoOracle extends javax.swing.JFrame {

    /**
     * Creates new form CertiificaadoOracle
     */
    public certificadoOracle() {
        initComponents();
        initConfig();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonJava = new javax.swing.JButton();
        jButtonIDE = new javax.swing.JButton();
        jButtonVariables = new javax.swing.JButton();
        jButtonOperations = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setPreferredSize(new java.awt.Dimension(1280, 660));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(53, 113, 173));

        jButtonJava.setBackground(new java.awt.Color(255, 255, 255));
        jButtonJava.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonJava.setForeground(new java.awt.Color(204, 0, 0));
        jButtonJava.setText("Java");
        jButtonJava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJavaActionPerformed(evt);
            }
        });

        jButtonIDE.setBackground(new java.awt.Color(255, 255, 255));
        jButtonIDE.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonIDE.setForeground(new java.awt.Color(204, 0, 0));
        jButtonIDE.setText("IDE");

        jButtonVariables.setBackground(new java.awt.Color(255, 255, 255));
        jButtonVariables.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonVariables.setForeground(new java.awt.Color(204, 0, 0));
        jButtonVariables.setText("Variables");
        jButtonVariables.setMargin(new java.awt.Insets(2, 10, 2, 10));

        jButtonOperations.setBackground(new java.awt.Color(255, 255, 255));
        jButtonOperations.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonOperations.setForeground(new java.awt.Color(204, 0, 0));
        jButtonOperations.setText("Operations");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonJava, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonIDE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonOperations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonVariables, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(371, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonJava)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonIDE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonVariables)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonOperations)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(790, 10, 480, 240);

        jScrollPane1.setBackground(new java.awt.Color(53, 113, 173));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(53, 113, 173));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setAutoscrolls(false);
        jTextArea1.setBorder(null);
        jTextArea1.setDisabledTextColor(new java.awt.Color(53, 113, 173));
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 40, 520, 560);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 0));
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 610, 67, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/javaBG1.png"))); // NOI18N
        jLabel1.setFocusable(false);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1340, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonJavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJavaActionPerformed
        // Java information
        
        String info="Java is a programation language comercialized for first time in 1995 by Sun Microsystems(Oracle Corporation actually). \n "
                + "Later in 1996 was derivated to JavaSoft for his developement."
                + "\n\n Java uses similar sintaxis from C/C++ but this one has lower\n"
                + " utilities of lower level. Java aplication are compiled to\n"
                + " bytcode to run in Java Virtual Machine (JVM) in any Operative  System of computer.";
        
        jTextArea1.setText(info);
        
    }//GEN-LAST:event_jButtonJavaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTextArea1.setText(" ");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(certificadoOracle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(certificadoOracle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(certificadoOracle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(certificadoOracle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new certificadoOracle().setVisible(true);
            }
        });
    }

    private void initConfig() {
        //Initial Configuration
        
        
        //Set Background color JFrame
        this.getContentPane().setBackground(Color.GRAY);
        //this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonIDE;
    private javax.swing.JButton jButtonJava;
    private javax.swing.JButton jButtonOperations;
    private javax.swing.JButton jButtonVariables;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
        
        
