/*
 *FECHA: 29/01/21
 *NAME
 */
package p.pkg21;

import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import javax.swing.JFrame;

/**
 *
 * @author magipedgay
 */
public class p21 extends javax.swing.JFrame {
//global declarations;

    private int dia, mes, anyo, bisest;

    //Constructor:
    public p21() {
        initComponents();
        initConfig();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxDia = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxMes = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxAnyo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldDiaNacimiento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jCheckBoxBisiesto = new javax.swing.JCheckBox();
        jLabelAnyo = new javax.swing.JLabel();
        jRadioButtonDiaMagico = new javax.swing.JRadioButton();
        jRadioButtonFechaEspecial = new javax.swing.JRadioButton();
        jRadioButtonFechaAlegre = new javax.swing.JRadioButton();
        jLabelDMeses = new javax.swing.JLabel();
        jTextFieldDiasMes = new javax.swing.JTextField();
        jLabelnNomMes = new javax.swing.JLabel();
        jTextFieldNomMes = new javax.swing.JTextField();
        jLabelDiasViv = new javax.swing.JLabel();
        jTextFieldDiasViv = new javax.swing.JTextField();
        jLabel5kDias = new javax.swing.JLabel();
        jTextField5kDias = new javax.swing.JTextField();
        jLabel10kDias = new javax.swing.JLabel();
        jTextField10kDias = new javax.swing.JTextField();
        jTextField20kDias = new javax.swing.JTextField();
        jLabel20kDias = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabelFoto = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setFocusable(false);
        setFocusableWindowState(false);
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(600, 600));
        setSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(48, 48, 48));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 204, 255));
        jLabel1.setText("Dia");

        jComboBoxDia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 204, 255));
        jLabel2.setText("Mes");

        jComboBoxMes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 204, 255));
        jLabel3.setText("Año");

        jComboBoxAnyo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxAnyo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setBackground(new java.awt.Color(0, 153, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Calculate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBoxDia, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jComboBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jComboBoxAnyo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxDia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxAnyo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(310, 0, 430, 170);

        jPanel2.setBackground(new java.awt.Color(48, 48, 48));

        jTextFieldDiaNacimiento.setFocusable(false);
        jTextFieldDiaNacimiento.setRequestFocusEnabled(false);
        jTextFieldDiaNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDiaNacimientoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 255));
        jLabel4.setText("Dia de Nacimiento");

        jCheckBoxBisiesto.setBackground(new java.awt.Color(48, 48, 48));
        jCheckBoxBisiesto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBoxBisiesto.setForeground(new java.awt.Color(0, 204, 255));
        jCheckBoxBisiesto.setText("Bisiesto");
        jCheckBoxBisiesto.setEnabled(false);
        jCheckBoxBisiesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxBisiestoActionPerformed(evt);
            }
        });

        jLabelAnyo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelAnyo.setForeground(new java.awt.Color(0, 204, 255));
        jLabelAnyo.setText("Año");

        jRadioButtonDiaMagico.setBackground(new java.awt.Color(48, 48, 48));
        jRadioButtonDiaMagico.setForeground(new java.awt.Color(0, 204, 255));
        jRadioButtonDiaMagico.setText("Dia mágico");
        jRadioButtonDiaMagico.setEnabled(false);

        jRadioButtonFechaEspecial.setBackground(new java.awt.Color(48, 48, 48));
        jRadioButtonFechaEspecial.setForeground(new java.awt.Color(0, 204, 255));
        jRadioButtonFechaEspecial.setText("Fecha Especial");
        jRadioButtonFechaEspecial.setEnabled(false);

        jRadioButtonFechaAlegre.setBackground(new java.awt.Color(48, 48, 48));
        jRadioButtonFechaAlegre.setForeground(new java.awt.Color(0, 204, 255));
        jRadioButtonFechaAlegre.setText("Fecha Alegre");
        jRadioButtonFechaAlegre.setEnabled(false);

        jLabelDMeses.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelDMeses.setForeground(new java.awt.Color(0, 204, 255));
        jLabelDMeses.setText("Dias del mes");

        jTextFieldDiasMes.setFocusable(false);
        jTextFieldDiasMes.setRequestFocusEnabled(false);
        jTextFieldDiasMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDiasMesActionPerformed(evt);
            }
        });

        jLabelnNomMes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelnNomMes.setForeground(new java.awt.Color(0, 204, 255));
        jLabelnNomMes.setText("Nombre del mes");

        jTextFieldNomMes.setFocusable(false);

        jLabelDiasViv.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelDiasViv.setForeground(new java.awt.Color(0, 204, 255));
        jLabelDiasViv.setText("Dias vividos");
        jLabelDiasViv.setFocusable(false);

        jTextFieldDiasViv.setFocusable(false);

        jLabel5kDias.setForeground(new java.awt.Color(0, 204, 255));
        jLabel5kDias.setText("5000 Dias");

        jTextField5kDias.setFocusable(false);
        jTextField5kDias.setRequestFocusEnabled(false);

        jLabel10kDias.setForeground(new java.awt.Color(0, 204, 255));
        jLabel10kDias.setText("10000 Dias");

        jTextField10kDias.setFocusable(false);
        jTextField10kDias.setRequestFocusEnabled(false);

        jTextField20kDias.setFocusable(false);
        jTextField20kDias.setRequestFocusEnabled(false);

        jLabel20kDias.setForeground(new java.awt.Color(0, 204, 255));
        jLabel20kDias.setText("20000 Dias");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelAnyo)
                        .addGap(27, 27, 27)
                        .addComponent(jCheckBoxBisiesto, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonDiaMagico)
                            .addComponent(jRadioButtonFechaEspecial)
                            .addComponent(jRadioButtonFechaAlegre))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20kDias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabelDiasViv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5kDias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel10kDias, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldDiasViv)
                            .addComponent(jTextField5kDias)
                            .addComponent(jTextField10kDias, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(jTextField20kDias))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldDiasMes, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDMeses))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelnNomMes)
                            .addComponent(jTextFieldNomMes, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(jTextFieldDiaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDiaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDMeses)
                    .addComponent(jLabelnNomMes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDiasMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNomMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAnyo)
                    .addComponent(jCheckBoxBisiesto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonDiaMagico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonFechaEspecial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonFechaAlegre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDiasViv)
                    .addComponent(jTextFieldDiasViv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5kDias)
                    .addComponent(jTextField5kDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10kDias)
                    .addComponent(jTextField10kDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField20kDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20kDias))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(20, 180, 280, 370);

        jPanel3.setBackground(new java.awt.Color(48, 48, 48));

        jLabelFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Yo.jpg"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 204, 255));
        jLabel5.setText("Max Pedregosa");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 204, 255));
        jLabel6.setText("Centre d'estudis Monlau");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelFoto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFoto)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(20, 30, 260, 110);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Waiting_web.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 800, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDiaNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDiaNacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDiaNacimientoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String diaStrg;
        dia = Integer.parseInt(jComboBoxDia.getSelectedItem().toString());
        mes = Integer.parseInt(jComboBoxMes.getSelectedItem().toString());
        anyo = Integer.parseInt(jComboBoxAnyo.getSelectedItem().toString());
        try {
            int day = FunctionDiasViv(dia, mes, anyo);
            jTextFieldDiasViv.setText(String.valueOf(day));
        } catch (ParseException ex) {
            System.out.println("Error");
        }

        diaStrg = functionDiaNacimiento(dia, mes, anyo);
        jTextFieldDiaNacimiento.setText(diaStrg);

        bisest = bisiest(anyo);
        if (bisest == 1) {
            jCheckBoxBisiesto.setSelected(true);
        } else {
            jCheckBoxBisiesto.setSelected(false);
        }

        int numbr = dia + mes + anyo;

        boolean Prim = PrimoFunct(numbr);
        boolean Alegre = fechaAlegre(numbr);
        boolean Especial = fechaEspecial(numbr);

        if (Prim == true) {
            jRadioButtonDiaMagico.setSelected(true);
            jRadioButtonFechaAlegre.setSelected(false);
            jRadioButtonFechaEspecial.setSelected(false);
        } else {
            jRadioButtonDiaMagico.setSelected(false);
            jRadioButtonFechaEspecial.setSelected(Especial);
            jRadioButtonFechaAlegre.setSelected(Alegre);
        }

        int diaMes;
        diaMes = FunctionDiaMes(mes, anyo);
        jTextFieldDiasMes.setText(diaMes + " Dias Totales");

        String NomMes = FunctionNomMes(mes);
        jTextFieldNomMes.setText(NomMes);
        
        String Dias5k = FunctionDDias5000(dia, mes, anyo);
        jTextField5kDias.setText(Dias5k);
        
        String Dias10k = FunctionDDias10000(dia, mes, anyo);
        jTextField10kDias.setText(Dias10k);
        
        String Dias20k = FunctionDDias20000(dia, mes, anyo);
        jTextField20kDias.setText(Dias20k);
        
        
        


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBoxBisiestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxBisiestoActionPerformed


    }//GEN-LAST:event_jCheckBoxBisiestoActionPerformed

    private void jTextFieldDiasMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDiasMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDiasMesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(p21.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(p21.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(p21.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(p21.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new p21().setVisible(true);
            }
        });
    }

    private void initConfig() {
        //Init configuration 

        //this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.getContentPane().setBackground(Color.GRAY);

        setValue();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBoxBisiesto;
    private javax.swing.JComboBox<String> jComboBoxAnyo;
    private javax.swing.JComboBox<String> jComboBoxDia;
    private javax.swing.JComboBox<String> jComboBoxMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10kDias;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20kDias;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel5kDias;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelAnyo;
    private javax.swing.JLabel jLabelDMeses;
    private javax.swing.JLabel jLabelDiasViv;
    private javax.swing.JLabel jLabelFoto;
    private javax.swing.JLabel jLabelnNomMes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButtonDiaMagico;
    private javax.swing.JRadioButton jRadioButtonFechaAlegre;
    private javax.swing.JRadioButton jRadioButtonFechaEspecial;
    private javax.swing.JTextField jTextField10kDias;
    private javax.swing.JTextField jTextField20kDias;
    private javax.swing.JTextField jTextField5kDias;
    private javax.swing.JTextField jTextFieldDiaNacimiento;
    private javax.swing.JTextField jTextFieldDiasMes;
    private javax.swing.JTextField jTextFieldDiasViv;
    private javax.swing.JTextField jTextFieldNomMes;
    // End of variables declaration//GEN-END:variables

    private void setValue() {
        jComboBoxDia.removeAllItems();
        jComboBoxMes.removeAllItems();
        jComboBoxAnyo.removeAllItems();

        for (int i = 1; i <= 31; i++) {
            jComboBoxDia.addItem(String.valueOf(i));

        }
        for (int i = 1; i <= 12; i++) {
            jComboBoxMes.addItem(String.valueOf(i));

        }
        for (int i = 1921; i <= 2010; i++) {
            jComboBoxAnyo.addItem(String.valueOf(i));

        }
    }

    private String functionDiaNacimiento(int dia, int mes, int anyo) {
        //Zeller
        String diaString = "";
        String[] semana = {"Domingo", "Lunes", "Martes", "Miercoles", "Viernes", "Sabado"};

        int a, y, m, d;
        dia = 28;
        a = (14 - mes) / 12;
        y = anyo - a;
        m = mes + 12 * a - 2;
        d = (dia + y + y / 4 - y / 100 + y / 400 + (31 * m) / 12) % 7;
        diaString = semana[d];

        return diaString;

    }

    private int bisiest(int anyo) {
        if (anyo % 4 == 0 && (anyo % 100 != 0 || anyo % 400 == 0)) {
            return 1;
        } else {
            return 0;
        }
    }

    private boolean PrimoFunct(int numbr) {
        int cntr = 2;
        boolean primo = true;
        while ((primo) && (cntr != numbr)) {
            if (numbr % cntr == 0) {
                primo = false;
            }
            cntr++;
        }
        return primo;
    }

    private boolean fechaAlegre(int numbr) {
        boolean alegre = false;
        if (numbr % 2 == 0) {
            alegre = true;
        }
        return alegre;
    }

    private boolean fechaEspecial(int numbr) {
        boolean Especial = false;
        if (numbr % 2 != 0) {
            Especial = true;
        }
        return Especial;

    }

    private int FunctionDiaMes(int mes, int anyo) {
        int dmes;
        int numDias[] = {0, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31};
        dmes = numDias[mes];
        if (mes == 2) {
            if (anyo % 4 == 0 && (anyo % 100 != 0 || anyo % 400 == 0)) {
                dmes = 29;
            } else {
                dmes = numDias[mes];
            }
        }

        return dmes;
    }

    private String FunctionNomMes(int mes) {

        String nomMes[] = {"", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"};
        return nomMes[mes];

    }

    private int FunctionDiasViv(int dia, int mes, int anyo) throws ParseException {
        int value = 0;
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        Date date1 = sdf.parse(dia + "/" + mes + "/" + anyo);
        Date date2 = new Date();
        long diff = date2.getTime() - date1.getTime();

        value = (int) TimeUnit.DAYS.convert(diff, TimeUnit.MILLISECONDS);

        return value;

    }

    private String FunctionDDias5000(int dia, int mes, int anyo) {
        String value = (LocalDate.of(anyo, mes, dia).plusDays(5000) + "");

        return value;

    }

    private String FunctionDDias10000(int dia, int mes, int anyo) {
        String value = (LocalDate.of(anyo, mes, dia).plusDays(10000) + "");

        return value;


    }

    private String FunctionDDias20000(int dia, int mes, int anyo) {
        String value = (LocalDate.of(anyo, mes, dia).plusDays(20000) + "");

        return value;

        
    }

}
